### ISSUE TITLE
Plugin fails when plugin's name is "archive" -  error converting Lua nil to function

### ISSUE THREAD

**Issue by ProfiGMan** [KKV9/compress.yazi#3]
Nothing happens when I press the key combination and through the task manager I was able to find this error:
`Micro plugin failed:
error converting Lua nil to function`

**Comment by KKV9** [comment]
I was able to reproduce this issue on the latest git version of yazi. Due to changes upstream, "archive" now is an illegal name for a plugin and must be renamed.

Try the following:
 -  Step 1

If on Unix:
```bash
mv ~/.config/yazi/plugins/archive.yazi/ ~/.config/yazi/plugins/compress.yazi/
```
If on Windows:
Navigate to %appdata%\yazi\plugins and rename archive.yazi to compress.yazi

 - Step 2
 
In your `keymap.toml` remove the old keybind and replace it with the following:
```toml
[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"
```
